#! /bin/sh

bspc monitor -d I II III IV V

bspc config border_width         1
bspc config focused_border_color  "#EBDBB2"
bspc config normal_border_color "#312F2E"
bspc config window_gap           15
bspc config focus_follows_pointer false


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty desktop='^1'
bspc rule -a qutebrowser desktop='^2'
bspc rule -a telegram-desktop desktop='^3'

sxhkd &
# picom --config ~/.config/bspwm/picom/picom.conf &
feh --bg-scale ~/.config/wallpaper/bridge-red-sky.jpg
~/.config/bspwm/polybar/launch.sh
