#! /bin/sh

bspc monitor -d I 
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         0
bspc config focused_border_color "#af17c4"
bspc config normal_border_color  "#111111"
bspc config window_gap           7
bspc config focus_follows_pointer true


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom  --config ~/.config/bspwm/picom/picom.conf &
feh --bg-scale /home/zedd/.config/wallpaper/simple.png
~/.config/bspwm/polybar/launch.sh
